[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "upv/etsiinf/aula1/people",
    "upv/etsiinf/aula1/idealpeople"
  ]
  data_format = "json"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "sensores"